apiVersion: v1
kind: Namespace
metadata:
  name: git-myan-application-samples-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git-myan-application-samples
  namespace: git-myan-application-samples-ns
spec:
  pathname: 'https://github.com/yanmxa/application-samples.git'
  type: Git
---
apiVersion: v1
kind: Namespace
metadata:
  name: pacman
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    apps.open-cluster-management.io/deployables: ''
  finalizers:
    - hub-of-hubs.open-cluster-management.io/resource-cleanup
  name: pacman-test
  namespace: pacman
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pacman
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: pacman
    apps.open-cluster-management.io/reconcile-option: merge
  finalizers:
    - hub-of-hubs.open-cluster-management.io/resource-cleanup
  labels:
    app: pacman
    app.kubernetes.io/part-of: pacman
    apps.open-cluster-management.io/reconcile-rate: medium
  name: pacman-appsub
  namespace: pacman
spec:
  channel: git-myan-application-samples-ns/git-myan-application-samples
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations: {}
  finalizers:
    - hub-of-hubs.open-cluster-management.io/resource-cleanup
  labels:
    app: pacman
  name: pacman-placement
  namespace: pacman
spec:
  clusterSelector:
    matchLabels:
      app: test
